Algoritmo "Entrada e Saida de Dados"
// Descrição   : Entrada e Saida de Dados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/04/2024
Var
// Seção de Declarações das variáveis 
   nome: caracter
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    leia (nome)
    leia (nota)
    
    escreval (nome)
    escreval (nota)

Fimalgoritmo